name: OpenAPI Publisher

on:
  workflow_call:
    secrets:
      README_API_KEY:
        required: true
      README_RESOURCE_API_ID:
        required: true
      README_AUTH_API_ID:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out repository

      - uses: readmeio/rdme@8.5.0
        name: Sync Open Payments API spec
        with:
          rdme: openapi resource-server.yaml --workingDirectory=openapi --key=${{ secrets.README_API_KEY }} --id=${{ secrets.README_RESOURCE_API_ID }}

      - uses: readmeio/rdme@8.5.0
        name: Sync Auth Server API spec
        with:
          rdme: openapi auth-server.yaml --workingDirectory=openapi --key=${{ secrets.README_API_KEY }} --id=${{ secrets.README_AUTH_API_ID }}
